-- MySQL Script generated by MySQL Workbench
-- Sun Mar  7 20:45:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `Customers_ID` VARCHAR(7) NOT NULL DEFAULT 'ID00000',
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `tel` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Customers_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Characters` (
  `username` VARCHAR(20) NOT NULL,
  `Characters_ID` VARCHAR(6) NOT NULL DEFAULT 'C00000',
  `charactername` VARCHAR(45) NOT NULL,
  `balance` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Characters_ID`),
  CONSTRAINT `fk_Character_Customers1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`Customers` (`Customers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventories` (
  `Characters_ID` VARCHAR(6) NOT NULL,
  `Inventories_ID` VARCHAR(6) NOT NULL DEFAULT 'I00000',
  `amount` INT(3) NOT NULL,
  PRIMARY KEY (`Inventories_ID`),
  INDEX `fk_Inventories_Characters1_idx` (`Characters_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Inventories_Characters1`
    FOREIGN KEY (`Characters_ID`)
    REFERENCES `mydb`.`Characters` (`Characters_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `charactername` VARCHAR(45) NOT NULL,
  `Order_ID` VARCHAR(6) NOT NULL DEFAULT 'O00000',
  `requiredDate` DATE NOT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `fk_Orders_Character1_idx` (`charactername` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Character1`
    FOREIGN KEY (`charactername`)
    REFERENCES `mydb`.`Characters` (`charactername`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemLists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemLists` (
  `ItemLists_ID` VARCHAR(6) NOT NULL DEFAULT 'L00000',
  `Item_Name` VARCHAR(100) NOT NULL,
  `Item_Detail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ItemLists_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shops` (
  `Shop_ID` VARCHAR(6) NOT NULL DEFAULT 'S00000',
  `priceEach` INT(8) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`Shop_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetails` (
  `Order_ID` VARCHAR(6) NOT NULL DEFAULT 'O00000',
  `OrderDetails_ID` VARCHAR(6) NOT NULL DEFAULT 'D00000',
  `ItemLists_ID` VARCHAR(6) NOT NULL DEFAULT 'L00000',
  `amount` INT NOT NULL DEFAULT 1,
  `Shop_ID` VARCHAR(6) NOT NULL DEFAULT 'S00000',
  PRIMARY KEY (`Order_ID`, `OrderDetails_ID`, `ItemLists_ID`, `Shop_ID`),
  INDEX `fk_OrderDetail_Orders1_idx` (`Order_ID` ASC) VISIBLE,
  INDEX `fk_OrderDetails_ItemList1_idx` (`ItemLists_ID` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Shops1_idx` (`Shop_ID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetail_Orders1`
    FOREIGN KEY (`Order_ID`)
    REFERENCES `mydb`.`Orders` (`Order_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_ItemList1`
    FOREIGN KEY (`ItemLists_ID`)
    REFERENCES `mydb`.`ItemLists` (`ItemLists_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_Shops1`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `mydb`.`Shops` (`Shop_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shops_has_ItemLists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shops_has_ItemLists` (
  `Shops_Shop_ID` VARCHAR(6) NOT NULL,
  `ItemLists_ItemLists_ID` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`Shops_Shop_ID`, `ItemLists_ItemLists_ID`),
  INDEX `fk_Shops_has_ItemLists_ItemLists1_idx` (`ItemLists_ItemLists_ID` ASC) VISIBLE,
  INDEX `fk_Shops_has_ItemLists_Shops1_idx` (`Shops_Shop_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Shops_has_ItemLists_Shops1`
    FOREIGN KEY (`Shops_Shop_ID`)
    REFERENCES `mydb`.`Shops` (`Shop_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shops_has_ItemLists_ItemLists1`
    FOREIGN KEY (`ItemLists_ItemLists_ID`)
    REFERENCES `mydb`.`ItemLists` (`ItemLists_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventories_has_ItemLists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventories_has_ItemLists` (
  `Inventories_Inventories_ID` VARCHAR(6) NOT NULL,
  `ItemLists_ItemLists_ID` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`Inventories_Inventories_ID`, `ItemLists_ItemLists_ID`),
  INDEX `fk_Inventories_has_ItemLists_ItemLists1_idx` (`ItemLists_ItemLists_ID` ASC) VISIBLE,
  INDEX `fk_Inventories_has_ItemLists_Inventories1_idx` (`Inventories_Inventories_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Inventories_has_ItemLists_Inventories1`
    FOREIGN KEY (`Inventories_Inventories_ID`)
    REFERENCES `mydb`.`Inventories` (`Inventories_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventories_has_ItemLists_ItemLists1`
    FOREIGN KEY (`ItemLists_ItemLists_ID`)
    REFERENCES `mydb`.`ItemLists` (`ItemLists_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
